#!/bin/sh
echo
printf "==============================================\n"
printf "Welcome to your Genomics Virtual Lab instance.\n"
printf "==============================================\n"
echo
printf " * Documentation: https://www.gvl.org.au/\n"
echo
